### PR TITLE
vimc-6541 add endpoint to get version list for report

### PR DESCRIPTION
**Pull request by hillalex**
The requirement for this was that OW should be able to check that a report exists: https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-6541

It seemed to me that implementing an endpoint which lists versions of a named report will suffice for that purpose while also being needed by OW elsewhere (e.g. to support this OW endpoint: https://github.com/vimc/orderly-web/blob/master/docs/spec/spec.md#get-reportsname)

So this PR adds:

`GET /report/:name` 

returning a list of version ids. If the list is empty, the report "doesn't exist" in the sense required by OW.

### CODE REVIEW

**Review by LekanAnni — APPROVED** [review]
LGTM 👍

**Review by LekanAnni — CHANGES_REQUESTED** [review]
I think we decided to use git folder for all OW, which means we would not need this endpoint again. The corresponding ticket for this PR was initially spec out to test whether a report exists or not, since it was decided to use Git folder in OW, the scope has changed. So, once we achieve usage of Git folder for OW, we will have access to reports data which we do not have using demo folder.

**Review by LekanAnni — APPROVED** [review]
👍

**Review by richfitz — APPROVED** [review]

**Comment by richfitz** [comment]
This looks good, but conflicts to fix  (probably straightforward but best for @hillalex to deal with)

**Pull request merged**
