### PR TITLE
VIMC-4539: Make branch & commit optional for available_reports endpoint

### PR DESCRIPTION
**Pull request by r-ash**
This PR will
* Make branch & commit optional for available_reports endpoint
* Make commit optional for endpoint_report_parameters

We added the logic to make this work as part of #41 but I never added an integration test to check it would work end to end - this fixed that.

### CODE REVIEW

**Review by mwoodbri — APPROVED** [review]
Have tested both endpoints with and without commit ID and works great :)

**Review by richfitz — APPROVED** [review]
LGTM - @mwoodbri, do you want to check that this solves the underlying issue or are you ok with the tests here?

**Comment by mwoodbri** [comment]
> LGTM - @mwoodbri, do you want to check that this solves the underlying issue or are you ok with the tests here?

Thanks - I failed to test something previously: listing reports when `git_supported` is false (rather than`master_only` being true).

@r-ash I know we discussed this earlier, but is the expectation that git is always enabled for repos being served by orderly.server? If not then `/reports/source` should handle this.

Tested by setting OrderlyWeb's `orderly_server_version` to `vimc-4539`, using the `demo` model and making a request to `localhost:8321/reports/source`. Error message `fatal: not a git repository (or any parent up to mount point`.

**Comment by r-ash** [comment]
> @r-ash I know we discussed this earlier, but is the expectation that git is always enabled for repos being served by orderly.server? If not then `/reports/source` should handle this.
> 
> Tested by setting OrderlyWeb's `orderly_server_version` to `vimc-4539`, using the `demo` model and making a request to `localhost:8321/reports/source`. Error message `fatal: not a git repository (or any parent up to mount point`.

Thanks, yes always expect that git is enabled. I'll make a ticket to make orderly.server refuse to start if git is not available.

**Pull request merged**
